# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import next_state_pb2 as next__state__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in next_state_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NextStateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/null_labs.next_state.v1.NextStateService/Health',
                request_serializer=next__state__pb2.HealthRequest.SerializeToString,
                response_deserializer=next__state__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.Initialize = channel.unary_unary(
                '/null_labs.next_state.v1.NextStateService/Initialize',
                request_serializer=next__state__pb2.InitializeRequest.SerializeToString,
                response_deserializer=next__state__pb2.InitializeResponse.FromString,
                _registered_method=True)
        self.NextState = channel.unary_unary(
                '/null_labs.next_state.v1.NextStateService/NextState',
                request_serializer=next__state__pb2.NextStateRequest.SerializeToString,
                response_deserializer=next__state__pb2.NextStateResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/null_labs.next_state.v1.NextStateService/Shutdown',
                request_serializer=next__state__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=next__state__pb2.ShutdownResponse.FromString,
                _registered_method=True)


class NextStateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Initialize(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def NextState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NextStateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=next__state__pb2.HealthRequest.FromString,
                    response_serializer=next__state__pb2.HealthResponse.SerializeToString,
            ),
            'Initialize': grpc.unary_unary_rpc_method_handler(
                    servicer.Initialize,
                    request_deserializer=next__state__pb2.InitializeRequest.FromString,
                    response_serializer=next__state__pb2.InitializeResponse.SerializeToString,
            ),
            'NextState': grpc.unary_unary_rpc_method_handler(
                    servicer.NextState,
                    request_deserializer=next__state__pb2.NextStateRequest.FromString,
                    response_serializer=next__state__pb2.NextStateResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=next__state__pb2.ShutdownRequest.FromString,
                    response_serializer=next__state__pb2.ShutdownResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'null_labs.next_state.v1.NextStateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('null_labs.next_state.v1.NextStateService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NextStateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/null_labs.next_state.v1.NextStateService/Health',
            next__state__pb2.HealthRequest.SerializeToString,
            next__state__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Initialize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/null_labs.next_state.v1.NextStateService/Initialize',
            next__state__pb2.InitializeRequest.SerializeToString,
            next__state__pb2.InitializeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def NextState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/null_labs.next_state.v1.NextStateService/NextState',
            next__state__pb2.NextStateRequest.SerializeToString,
            next__state__pb2.NextStateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/null_labs.next_state.v1.NextStateService/Shutdown',
            next__state__pb2.ShutdownRequest.SerializeToString,
            next__state__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
